name: lando-drupal9
recipe: drupal9
config:
  webroot: .
  xdebug: true
  config:
    php: .vscode/php.ini
services:
  phpmyadmin:
    type: phpmyadmin
    host:
      - database
  mailhog:
    type: mailhog
    hogform:
      - appserver
